// ========== Live News Loader for Iran War News Tracker ==========
// Loads live-news.json (auto-generated by GitHub Actions every 3 hours)
// Falls back to static data in news-data.js if JSON is unavailable

/**
 * Fetch live news from the pre-generated JSON file.
 * @param {Function} onProgress - callback(completed, total)
 * @returns {Promise<Array>} array of article objects
 */
async function fetchAllLiveNews(onProgress) {
    try {
        if (onProgress) onProgress(1, 3);

        // Add cache-busting timestamp so browsers don't serve stale JSON
        const cacheBust = `?t=${Date.now()}`;
        const resp = await fetch('live-news.json' + cacheBust, {
            signal: AbortSignal.timeout(10000)
        });

        if (onProgress) onProgress(2, 3);

        if (!resp.ok) {
            console.warn('live-news.json not found (HTTP ' + resp.status + '), using static data');
            return [];
        }

        const data = await resp.json();

        if (!data.articles || !Array.isArray(data.articles)) {
            console.warn('live-news.json has invalid format, using static data');
            return [];
        }

        if (onProgress) onProgress(3, 3);

        console.log(`Loaded ${data.articles.length} live articles (updated: ${data.lastUpdated})`);
        return data.articles;

    } catch (err) {
        console.warn('Failed to load live-news.json:', err.message);
        return [];
    }
}
